# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -g

# Default target
all:
	$(CXX) $(CXXFLAGS) -o program2 lambda_exp.cpp
	./program2

# Clean target
clean:
	@echo "Cleaning up..."
	@del program1.exe
